spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    application:
      name: profile
security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      user-authorization-uri: http://localhost:9191/oauth/authorize
      access-token-uri:  http://localhost:9191/oauth/token
    resource:
      token-info-uri:   http://localhost:9191/oauth/check_token
server:
  servlet:
    session:
      cookie:
        name: ASESSION


