spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    application:
      name: profile
  security:
    oauth2:
    resource:
      token-info-url: http://localhost:9191/oauth/check_token
    client-id: mobile
    client-secret: pin
